/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_MetodiNativi */

#ifndef _Included_com_company_MetodiNativi
#define _Included_com_company_MetodiNativi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_MetodiNativi
 * Method:    CreateCode
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_company_MetodiNativi_CreateCode
  (JNIEnv *, jclass);

/*
 * Class:     com_company_MetodiNativi
 * Method:    UserInput
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_company_MetodiNativi_UserInput
  (JNIEnv *, jclass);

/*
 * Class:     com_company_MetodiNativi
 * Method:    Controllo
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_com_company_MetodiNativi_Controllo
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
